/*
 * Copyright © 2018 ZSO Bern Plus
 *
 * This file is part of Zivilschutzkarte 2.
 *
 * Zivilschutzkarte 2 is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the 
 * Free Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * Zivilschutzkarte 2 is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Zivilschutzkarte 2.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 */


import {Sign} from "../entity/sign";

export class Signs {

    public static SIGNS: Sign[] = [
        {
            type: "Point",
            kat: "blue",
            src: "ABC Dekontaminationsstelle.png",
            de: "ABC Dekontaminationsstelle",
            en: "ABC Dekontaminationsstelle",
            fr: "Place de décontamination",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "blue",
            src: "Absperrung Einsatzraum.png",
            de: "Absperrung Einsatzraum",
            en: "Absperrung Einsatzraum",
            fr: "Barrage du secteur d’engagement",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Absperrung Verkehrswege.png",
            de: "Absperrung Verkehrswege",
            en: "Absperrung Verkehrswege",
            fr: "Fermeture de la route",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Achse fuer Ei, Rttg, Vsg.png",
            de: "Achse fuer Ei, Rttg, Vsg",
            en: "Achse fuer Ei, Rttg, Vsg",
            fr: "Axe d’engagement pour le sauvetage, l’approvisionnement, etc.",
            style: "dash",
            text: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Angehoerigensammelstelle.png",
            de: "Angehoerigensammelstelle",
            en: "Angehoerigensammelstelle",
            fr: "Poste collecteur pour les proches",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Atomunfall.png",
            de: "Atomunfall",
            en: "Atomunfall",
            fr: "Accident nucléaire",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Autounfall_2.png",
            de: "Autounfall",
            en: "Autounfall",
            fr: "Accident de circulation automobile",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Beabsichtigte Erkundung.png",
            de: "Beabsichtigte Erkundung",
            en: "Beabsichtigte Erkundung",
            fr: "Exploration / Reconnaissances prévues",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Beabsichtigter Einsatz.png",
            de: "Beabsichtigter Einsatz",
            en: "Beabsichtigter Einsatz",
            fr: "Engagements prévus",
            style: "dash",
            text: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Beabsichtigte Verschiebung.png",
            de: "Beabsichtigte Verschiebung",
            en: "Beabsichtigte Verschiebung",
            fr: "Mouvements prévus",
            style: "dash",
            text: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Beobachtung.png",
            de: "Beobachtung",
            en: "Beobachtung",
            fr: "Observation",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Beschaedigung.png",
            de: "Beschädigung",
            en: "Beschäigung",
            fr: "Dégât",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Betreuungsstelle.png",
            de: "Betreuungsstelle",
            en: "Betreuungsstelle",
            fr: "Poste d’assistance",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Betriebsstoffabgabestelle.png",
            de: "Betriebsstoffabgabestelle",
            en: "Betriebsstoffabgabestelle",
            fr: "Station de carburant",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Bezirksfuehrungsorgan.png",
            de: "Bezirksfuehrungsorgan",
            en: "Bezirksfuehrungsorgan",
            fr: "Organe de conduite de district",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "other",
            src: "Biologisch verseuchtes Gebiet.png",
            de: "Biologisch verseuchtes Gebiet",
            en: "Biologisch verseuchtes Gebiet",
            fr: "Zone biologiquement contaminée",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Biounfall.png",
            de: "Biounfall",
            en: "Biounfall",
            fr: "Accident biologique",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "B Laboratorium.png",
            de: "B Laboratorium",
            en: "B Laboratorium",
            fr: "Laboratoire B",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Bombenanschlag.png",
            de: "Bombenanschlag",
            en: "Bombenanschlag",
            fr: "Attentat à la bombe",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Bombendrohung.png",
            de: "Bombendrohung",
            en: "Bombendrohung",
            fr: "Menace à la bombe",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Brandanschlag.png",
            de: "Brandanschlag",
            en: "Brandanschlag",
            fr: "Incendie criminel",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Brand einzelnes Gebaeude Flamme.png",
            de: "Brand einzelnes Gebaeude Flamme",
            en: "Brand einzelnes Gebaeude Flamme",
            fr: "Incendie isolé",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Brand.png",
            de: "Brand",
            en: "Brand",
            fr: "Incendie",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "red",
            src: "Branduebergriff erfolgt - Signatur.png",
            de: "Brandübergriff erfolgt",
            en: "Brandübergriff erfolgt",
            fr: "Extension du feu",
            example: "Branduebergriff erfolgt - Beispiel.png",
            text: null,
            style: null,
            fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "red",
            src: "Branduebergriffsgefahr - Signatur.png",
            de: "Brandübergriffsgefahr",
            en: "Brandübergriffsgefahr",
            fr: "Danger d'extension",
            example: "Branduebergriffsgefahr - Beispiel.png",
            style: "dash",
            text: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Brandzone Flaechenbrand.png",
            de: "Brandzone Flächenbrand",
            en: "Brandzone Flächenbrand",
            fr: "Zone en feu",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Chemieunfall.png",
            de: "Chemieunfall",
            en: "Chemieunfall",
            fr: "Accident chimique",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "other",
            src: "Chemievergiftetes Gebiet gasfoermig - fluechtig.png",
            de: "Chemievergiftetes Gebiet gasförmig - flüchtig",
            en: "Chemievergiftetes Gebiet gasförmig - flüchtig",
            fr: "Zone chimiquement contaminée gazeux - volatil",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "other",
            src: "Chemievergiftete Zone fluessig - sesshaft.png",
            de: "Chemievergiftete Zone flüssig - sesshaft",
            en: "Chemievergiftete Zone flüssig - sesshaft",
            fr: "Zone chimiquement contaminée liquide",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Chemikalien.png",
            de: "Chemikalien",
            en: "Chemikalien",
            fr: "Chimique",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Debriefingstelle.png",
            de: "Debriefingstelle",
            en: "Debriefingstelle",
            fr: "Poste de débriefing",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Demo gewaltlos.png",
            de: "Demo gewaltlos",
            en: "Demo gewaltlos",
            fr: "Manifestation",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Demo gewaltsam.png",
            de: "Demo gewaltsam",
            en: "Demo gewaltsam",
            fr: "Manifestation avec exactions",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Drohung.png",
            de: "Drohung",
            en: "Drohung",
            fr: "Menace",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Duerre.png",
            de: "Dürre",
            en: "Dürre",
            fr: "Sécheresse",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Durchgefuehrte Erkundung.png",
            de: "Durchgeführte Erkundung",
            en: "Durchgeführte Erkundung",
            fr: "Exploration / Reconnaissances exécutées",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Durchgefuehrter Einsatz.png",
            de: "Durchgeführter Einsatz",
            en: "Durchgeführter Einsatz",
            fr: "Engagements exécutés",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Durchgefuehrte Verschiebung.png",
            de: "Durchgeführte Verschiebung",
            en: "Durchgeführte Verschiebung",
            fr: "Mouvements exécutés",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Eingesperrte - Abgeschnittene.png",
            de: "Eingesperrte - Abgeschnittene",
            en: "Eingesperrte - Abgeschnittene",
            fr: "Personnes enfermées ou retranchées",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Einsatzleiter.png",
            de: "Einsatzleiter",
            en: "Einsatzleiter",
            fr: "Chef d’intervention",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Einsatzleitung.png",
            de: "Einsatzleitung",
            en: "Einsatzleitung",
            fr: "Direction d’intervention",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Einsatzzentrale.png",
            de: "Einsatzzentrale",
            en: "Einsatzzentrale",
            fr: "Centrale d‘engagement",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Eisenbahnunglueck.png",
            de: "Eisenbahnunglück",
            en: "Eisenbahnunglück",
            fr: "Accident ferroviaire",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Elektrizitaet.png",
            de: "Elektrizität",
            en: "Elektrizität",
            fr: "Electricité",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Energieausfall.png",
            de: "Energieausfall",
            en: "Energieausfall",
            fr: "Panne énergétique",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Epidemie.png",
            de: "Epidemie",
            en: "Epidemie",
            fr: "Epidemie",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Erdbeben.png",
            de: "Erdbeben",
            en: "Erdbeben",
            fr: "Tremblement de terre",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Erdrutsch.png",
            de: "Erdrutsch",
            en: "Erdrutsch",
            fr: "Glissement de terrain",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Explosion.png",
            de: "Explosion",
            en: "Explosion",
            fr: "Explosion",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Explosionsherd - Signatur.png",
            de: "Explosionsherd",
            en: "Explosionsherd",
            fr: "Foyer d’explosion",
            example: "Explosionsherd - Beispiel.png",
            text: null,
            style: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Fahrzeugplatz.png",
            de: "Fahrzeugplatz",
            en: "Fahrzeugplatz",
            fr: "Place pour véhicules",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Fluechtlinge.png",
            de: "Flüchtlinge",
            en: "Flüchtlinge",
            fr: "Réfugiés",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Flugzeugabsturz.png",
            de: "Flugzeugabsturz",
            en: "Flugzeugabsturz",
            fr: "Catastrophe aérienne",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Gas.png",
            de: "Gas",
            en: "Gas",
            fr: "Gaz",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Gebaeudeeinsturz.png",
            de: "Gebäudeeinsturz",
            en: "Gebäudeeinsturz",
            fr: "Immeuble effondré",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Gefahr durch Loeschen mit Wasser.png",
            de: "Gefahr durch Löschen mit Wasser",
            en: "Gefahr durch Löschen mit Wasser",
            fr: "Danger en cas d'extinction avec de l'eau",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Gefahrentafel mit UN-Nummer.png",
            de: "Gefahrentafel mit UN-Nummer",
            en: "Gefahrentafel mit UN-Nummer",
            fr: "Plaque de danger avec numéro ONU",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Gefahr fuer Grundwasser.png",
            de: "Gefahr fuer Grundwasser",
            en: "Gefahr fuer Grundwasser",
            fr: "Danger pour les eaux de surface et/ou nappes souterraines",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Gemeindefuehrungsorgan.png",
            de: "Gemeindeführungsorgan",
            en: "Gemeindeführungsorgan",
            fr: "Organe de conduite communal",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Gruppenfuehrer.png",
            de: "Gruppenführer",
            en: "Gruppenführer",
            fr: "Chef de groupe",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Gruppe.png",
            de: "Gruppe",
            en: "Gruppe",
            fr: "Groupe",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Helikopterlandeplatz.png",
            de: "Helikopterlandeplatz",
            en: "Helikopterlandeplatz",
            fr: "Place d’atterrissage pour hélicoptère",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Informationsstelle.png",
            de: "Informationsstelle",
            en: "Informationsstelle",
            fr: "Point d’information",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Informationszentrum.png",
            de: "Informationszentrum",
            en: "Informationszentrum",
            fr: "Centre de presse",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Infrastrukturschaden.png",
            de: "Infrastrukturschaden",
            en: "Infrastrukturschaden",
            fr: "Dommages aux infrastructures",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Kadaversammelstelle.png",
            de: "Kadaversammelstelle",
            en: "Kadaversammelstelle",
            fr: "Poste collecteur de cadavres d’animaux",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Kanalisationsausfall.png",
            de: "Kanalisationsausfall",
            en: "Kanalisationsausfall",
            fr: "Egoûts défectueux",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Kantonales Fuehrungsorgan.png",
            de: "Kantonales Führungsorgan",
            en: "Kantonales Führungsorgan",
            fr: "Organe de conduite cantonal",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "KGS Sammelpunkt.png",
            de: "KGS Sammelpunkt",
            en: "KGS Sammelpunkt",
            fr: "Point de collecte PBC",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Kommandoposten Front.png",
            de: "Kommandoposten Front",
            en: "Kommandoposten Front",
            fr: "PC engagement",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Kommandoposten Rueckwaertiges.png",
            de: "Kommandoposten Rückwärtiges",
            en: "Kommandoposten Rückwärtiges",
            fr: "PC opérations",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Kommunikationsstoerung.png",
            de: "Kommunikationsstörung",
            en: "Kommunikationsstörung",
            fr: "Perturbation de la communication",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Kompanie.png",
            de: "Kompanie",
            en: "Kompanie",
            fr: "Compagnie",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Kontrollstelle.png",
            de: "Kontrollstelle",
            en: "Kontrollstelle",
            fr: "Point de contrôle",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Kontrollzentrum.png",
            de: "Kontrollzentrum",
            en: "Kontrollzentrum",
            fr: "Centre de contrôle",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Lawine.png",
            de: "Lawine",
            en: "Lawine",
            fr: "Avalanche",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Massenpanik.png",
            de: "Massenpanik",
            en: "Massenpanik",
            fr: "Effets de panique",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Materialdepot.png",
            de: "Materialdepot",
            en: "Materialdepot",
            fr: "Dépôt de matériel",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Mobile Einsatzzentrale.png",
            de: "Mobile Einsatzzentrale",
            en: "Mobile Einsatzzentrale",
            fr: "Centrale d’engagement mobile",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Obdachlose.png",
            de: "Obdachlose",
            en: "Obdachlose",
            fr: "Sans-abri",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Oelverschmutzung.png",
            de: "Ölverschmutzung",
            en: "Ölverschmutzung",
            fr: "Pollution aux hydrocarbures",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Offizier - Zugfuehrer.png",
            de: "Offizier - Zugführer",
            en: "Offizier - Zugführer",
            fr: "Officier",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Patientensammelstelle.png",
            de: "Patientensammelstelle",
            en: "Patientensammelstelle",
            fr: "Poste collecteur de patients",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Pforte.png",
            de: "Pforte",
            en: "Pforte",
            fr: "Porte",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Pluenderung.png",
            de: "Plünderung",
            en: "Plünderung",
            fr: "Pillage",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "other",
            src: "Radioaktives Gebiet.png",
            de: "Radioaktives Gebiet",
            en: "Radioaktives Gebiet",
            fr: "Zone radioactive",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Radioaktive Stoffe.png",
            de: "Radioaktive Stoffe",
            en: "Radioaktive Stoffe",
            fr: "Substances radioactives",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Regionales Fuehrungsorgan.png",
            de: "Regionales Führungsorgan",
            en: "Regionales Führungsorgan",
            fr: "Organe de conduite régional",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Rutschgebiet.png",
            de: "Rutschgebiet",
            en: "Rutschgebiet",
            fr: "Glissement de terrain",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Sabotage.png",
            de: "Sabotage",
            en: "Sabotage",
            fr: "Sabotage",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Sammelstelle.png",
            de: "Sammelstelle",
            en: "Sammelstelle",
            fr: "Poste collecteur",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Sanitaetshilfsstelle.png",
            de: "Sanitätshilfsstelle",
            en: "Sanitätshilfsstelle",
            fr: "Poste médical avancé",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Sanitaetsumladestelle.png",
            de: "Sanitätsumladestelle",
            en: "Sanitätsumladestelle",
            fr: "Poste sanitaire de transfert",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Sperre.png",
            de: "Sperre",
            en: "Sperre",
            fr: "Barrage",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Standort mobile Fuehrungsstelle.png",
            de: "Standort mobile Führungsstelle",
            en: "Standort mobile Führungsstelle",
            fr: "Poste de conduite",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Starkniederschlag.png",
            de: "Starkniederschlag",
            en: "Starkniederschlag",
            fr: "Fortes précipitations",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Stau.png",
            de: "Stau",
            en: "Stau",
            fr: "Embouteillage",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "red",
            src: "Str erschwert befahrbar - begehbar.png",
            de: "Strasse erschwert befahrbar - begehbar",
            en: "Strasse erschwert befahrbar - begehbar",
            fr: "Route difficilement praticable pour les vhc, possible pour les piétons",
            style: "dash",
            text: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Streugutsammelstelle.png",
            de: "Streugutsammelstelle",
            en: "Streugutsammelstelle",
            fr: "Poste collecteur des objets trouvés",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "red",
            src: "Str nicht befahrbar - schwer begehbar.png",
            de: "Strasse nicht befahrbar - schwer begehbar",
            en: "Strasse nicht befahrbar - schwer begehbar",
            fr: "Route impraticable pour les vhc et difficile pour les piétons",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "red",
            src: "Str unpassierbar - gesperrt.png",
            de: "Strasse unpassierbar - gesperrt",
            en: "Strasse unpassierbar - gesperrt",
            fr: "Route impraticable / barrée",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Stuetzpunkt.png",
            de: "Stützpunkt",
            en: "Stützpunkt",
            fr: "Point de sécurité",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Sturm.png",
            de: "Sturm",
            en: "Sturm",
            fr: "Tempête",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Tankloeschfahrzeug.png",
            de: "Tanklöschfahrzeug",
            en: "Tanklöschfahrzeug",
            fr: "Tonne-pompe",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Teilzerstoerung.png",
            de: "Teilzerstörung",
            en: "Teilzerstörung",
            fr: "Destruction partielle",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Terroranschlag.png",
            de: "Terroranschlag",
            en: "Terroranschlag",
            fr: "Acte de terrorisme",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Tierseuche.png",
            de: "Tierseuche",
            en: "Tierseuche",
            fr: "Epizootie",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Totalzerstoerung.png",
            de: "Totalzerstörung",
            en: "Totalzerstörung",
            fr: "Destruction totale",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Totensammelstelle.png",
            de: "Totensammelstelle",
            en: "Totensammelstelle",
            fr: "Poste collecteur de cadavres",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Tote.png",
            de: "Tote",
            en: "Tote",
            fr: "Morts",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Trinkwasserabgabestelle.png",
            de: "Trinkwasserabgabestelle",
            en: "Trinkwasserabgabestelle",
            fr: "Poste de distribution d’eau potable",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Trupp.png",
            de: "Trupp",
            en: "Trupp",
            fr: "Patrouille",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Ueberschwemmtes Gebiet.png",
            de: "Überschwemmtes Gebiet",
            en: "Überschwemmtes Gebiet",
            fr: "Zone inondée ou submergée",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Ueberschwemmung.png",
            de: "Überschwemmung",
            en: "Überschwemmung",
            fr: "Inondation",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Ueberwachung.png",
            de: "Überwachung",
            en: "Überwachung",
            fr: "Surveillance",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "LineString",
            kat: "blue",
            src: "Umleitung.png",
            de: "Umleitung",
            en: "Umleitung",
            fr: "Déviations",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "orange",
            src: "Unfall.png",
            de: "Unfall",
            en: "Unfall",
            fr: "Accident",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Verkehrsposten.png",
            de: "Verkehrsposten",
            en: "Verkehrsposten",
            fr: "Poste de circulation",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Verletztennest.png",
            de: "Verletztennest",
            en: "Verletztennest",
            fr: "Nid de blessés",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Verletzte.png",
            de: "Verletzte",
            en: "Verletzte",
            fr: "Patients (blessés)",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Vermisste.png",
            de: "Vermisste",
            en: "Vermisste",
            fr: "Disparus",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Verpflegungsabgabestelle.png",
            de: "Verpflegungsabgabestelle",
            en: "Verpflegungsabgabestelle",
            fr: "Poste de distribution de subsistance",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "red",
            src: "Wasservsgausfall.png",
            de: "Wasserversorgungsausfall",
            en: "Wasserversorgungsausfall",
            fr: "Interruption de l’approvisionnement en eau",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Wasserwerfer.png",
            de: "Wasserwerfer",
            en: "Wasserwerfer",
            fr: "Canon à eau",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Polygon",
            kat: "red",
            src: "Zerstoerte Zone einer Ortschaft.png",
            de: "Zerstörte Zone einer Ortschaft",
            en: "Zerstörte Zone einer Ortschaft",
            fr: "Zone sinistrée, impraticable à l’intérieur d’une localité",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        },
        {
            type: "Point",
            kat: "blue",
            src: "Zug.png",
            de: "Zug",
            en: "Zug",
            fr: "Section",
            text: null,
            style: null,
            example: null, fillOpacity: null, color: null, dataUrl: null
        }
    ]
}